all: 
	@echo "This Makefile is only for the CVS repository"
	@echo "I will delete it before making the distribution"
	@echo ""
	aclocal 
	autoheader
	automake
	autoconf

dist:
	aclocal 
	autoheader
	automake --foreign --include-deps
	autoconf
	pwd
	LIST=`find ./po -name "*.po"`
	echo `find ./po -name "*.po"`
	for i in `find ./po -name "*.po"`; do \
	 file2=`echo $i | sed -e "s#\.po#\.gmo#"`; \
	 msgfmt -o $(file2) $i; \
	done

