#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
# $XConsortium: TakeConsole,v 1.2 93/09/28 14:30:29 gildea Exp $
# $Id: TakeConsole,v 1.3 1998/09/30 21:20:26 bieker Exp $
#
#chmod 622 /dev/console
#chown root /dev/console
