#!/bin/sh
# $XConsortium: Xsession /main/10 1995/12/18 18:21:28 gildea $
# $Id: Xsession,v 1.6 1998/09/29 16:49:02 bieker Exp $

# redirect errors to a file in user's home directory if we can
for errfile in "$HOME/.xsession-errors" "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
do
	if ( cp /dev/null "$errfile" 2> /dev/null )
	then
		chmod 600 "$errfile"
		exec > "$errfile" 2>&1
		break
	fi
done

case $# in
1)
	case $1 in
	failsafe)
		exec xterm -geometry 80x24-0-0
		;;
	esac
esac

# start windowmanager
which -s "$1" && exec "$1"

# windowmanager not found, tell user
message="Sorry, $1 not found."
if which -s "$1"; then
  exec kdialog --msgbox "$message"
else
  exec xmessage -center "$message"
fi
