#!/bin/sh
#
# /etc/X11/kdm/Xreset_0
#
# This script is run as root after the session on :0 ends.

# Call the global Xreset script, if it exists
if [ -x /etc/X11/kdm/Xreset ]; then
  /etc/X11/kdm/Xreset
fi

# :0 specific reset commands go here

exit 0
