#! /bin/sh
# postrm script for kdm
#     
# see: dh_installdeb(1)

set -e

case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       ;;
       purge)
         rm -rf /usr/X11R6/lib/X11/kdm
       ;;

    update-rc.d kdm remove >/dev/null
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0


esac   

#DEBHELPER#
#KDEHELPER#

exit 0
