#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
  update-rc.d kdm defaults 99 01 >/dev/null
fi  

chmod +x /etc/menu-methods/kde

window_manager_entry='/usr/X11R6/bin/kde'
if ! grep -q "^$window_manager_entry$" /etc/X11/window-managers 
then
	echo $window_manager_entry >> /etc/X11/window-managers 
        echo "Installed kde in the window-manager list."
fi
 
echo "Updating kdmrc ..."
grep -vE "^(NoUsers|GUIStyle|SessionTypes)" /etc/kde/kdmrc > /tmp/kdmrc
echo "[KDM]" >> /tmp/kdmrc  
echo -n "NoUsers=" >> /tmp/kdmrc
for user in `sed -e "s#^\([^:]*\):.*:\([0-9]*\):.*\$#\2-\1#" /etc/passwd`; do 
    id=`echo $user | sed -e "s#-.*##"`
    if test -n "$id" && expr "$id" \> 1000 && expr "$id" \< 65500; then
	echo -n "`echo $user | sed -e "s#[0-9]*-##"`;" >> /tmp/kdmrc
    fi
done
echo "" >> /tmp/kdmrc
echo -n "SessionTypes=kde" >> /tmp/kdmrc
for session in `grep -v "^#" | sed -e 's#^.*/\([^/]*\)$#\1#' | sort -u | grep -v kde`; do
    echo -n "$session;" >> /tmp/kdmrc
done
-mv /tmp/kdmrc /etc/kde/kdmrc

if test ! -L /var/spool/kdeapplnk; then
	ln -s /usr/share/applnk/debian_menu /var/spool/kdeapplnk
fi

#DEBHELPER#

# Starting kdm
/etc/init.d/kdm start
