#!/bin/sh

set -e

case "$1" in
remove)
	grep -v '\<kde\>' /etc/X11/window-managers > /etc/X11/window-managers.temp
	mv /etc/X11/window-managers.temp /etc/X11/window-managers
	grep -v "^start-kdm" /etc/X11/config > /etc/X11/config.tmp 
	mv /etc/X11/config.tmp /etc/X11/config
	rm -rf /usr/share/applnk/debian_menu
	;; 
purge)
    update-rc.d kdm remove >/dev/null
    ;;

esac   
#DEBHELPER#
