#!/bin/sh

set -e

if [ -x /usr/sbin/register-window-manager ]; then
  /usr/sbin/register-window-manager --remove /usr/X11/bin/kwm
  /usr/sbin/register-window-manager --remove /usr/X11/bin/kde
  /usr/sbin/register-window-manager --remove /usr/bin/kwm
fi



case "$1" in
        upgrade) 
	if test -L /var/spool/kdeapplnk; then
	    rm -f /var/spool/kdeapplnk
	fi
	if test /usr/share/applnk/debian_menu; then
	    rm -rf /usr/share/applnk/debian_menu
	fi
	;;
esac   
