#!/bin/bash

set -e

case "$1" in
        remove) 
	if test -n "`/sbin/pidof kdm`"
	then /etc/init.d/kdm stop 
	fi ;;
        purge) 
	if test -n "`/sbin/pidof kdm`"
	then /etc/init.d/kdm stop 
	fi ;;
esac
          
