#!/bin/sh

# based on xbase-configure script from xbase package :-)

set -e

xdmserver=0
kdmserver=0

if grep -q ^start-xdm /etc/X11/kdm/config
then
    xdmserver=1
fi

if grep -q ^start-kdm /etc/X11/kdm/config
then
    kdmserver=1
fi

echo "current configuration :" 
case $xdmserver in
	0)	echo "don't start xdm "
		;;
	1) 	echo "start xdm"
		;;
esac

case $kdmserver in
	0)	echo "don't start kdm"
		;;
	1) 	echo "start kdm"
		;;
esac

echo 
echo 'Do you want : '
echo '		1)	start xdm'
echo ' 		2)	start kdm'
echo '		3)	none'
echo 
echo -n 'Your choice ? (1/2/3) [2] '
read input
case "$input" in
	1)	xdmserver=1; kdmserver=2; ;;
	2)	xdmserver=2; kdmserver=1; ;;
	3)	xdmserver=2; kdmserver=2; ;;
	*)	xdmserver=2; kdmserver=1; ;;
esac
echo "# KDM - XDM Startup config thing" >> /etc/X11/kdm/config.new

xdm=0
test -n "`pidof xdm`" && xdm=1
if [ $xdmserver -eq 1 ] ; then
	echo "start-xdm" >> /etc/X11/kdm/config.new
	if [ $xdm -eq 0 ]; then start=xdm; fi
else
	if [ $xdm -eq 1 ]; then stop=xdm; fi
fi

kdm=0
test -n "`pidof kdm`" && kdm=1
if [ $kdmserver -eq 1 ] ; then
	echo "start-kdm" >> /etc/X11/kdm/config.new
	if [ $kdm -eq 0 ]; then start=kdm; fi
else
	if [ $kdm -eq 1 ]; then stop=kdm; fi
fi

mv /etc/X11/kdm/config.new /etc/X11/kdm/config
sleep 2

if test -n "$stop" -a -n "$start"
then
	echo "i need to stop $stop and start $start"
	echo "/etc/init.d/$stop stop"
	echo "/etc/init.d/$start start"
	default=y
	test -n "$DISPLAY" && default=n
	echo -n "Continue ? (y/n) [$default]"
	read answer
	test -z "$answer" && answer=$default
	case $answer in
		y*|Y*)	/etc/init.d/$stop stop 
			;;
	esac
	case $answer in
		y*|Y*)	/etc/init.d/$start start
			;;
	esac
elif test -n "$stop"
then
	echo "i need to stop $stop "
	echo "/etc/init.d/$stop stop"
	default=y
	test -n "$DISPLAY" && default=n
	echo -n "Continue ? (y/n) [$default]"
	read answer
	test -z "$answer" && answer=$default
	case $answer in
		y*|Y*)	/etc/init.d/$stop stop 
			;;
	esac
elif test -n "$start"
then
	echo "i need to start $start"
	echo "/etc/init.d/$start start"
	default=y
	test -n "$DISPLAY" && default=n
	echo -n "Continue ? (y/n) [$default]"
	read answer
	test -z "$answer" && answer=$default
	case $answer in
		y*|Y*)	/etc/init.d/$start start
			;;
	esac
fi


exit 0
