# Generated automatically from Makefile.in by configure.

PIXDIR		= /home/kulow/prod/kde/lib/pics
mkinstalldirs   = $(SHELL) ../../././mkinstalldirs
INSTALL_DATA	= /home/kulow/bin/install -c -m 0644

default:

install:
	$(mkinstalldirs) $(PIXDIR)
	$(mkinstalldirs) $(PIXDIR)/users
	$(INSTALL_DATA) kdelogo.xpm $(PIXDIR)
	$(INSTALL_DATA) default.xpm root.xpm $(PIXDIR)/users

clean:
	$(RM) core *~