#!/bin/sh

echo "This files installs KFM on your personal account"
echo
echo "Creating directories in ~/Desktop"
echo

install -d -m 0700 $HOME/.kfm
install -d -m 0700 $HOME/.kfm/cache
install -d -m 0700 $HOME/Desktop
install -d -m 0700 $HOME/Desktop/Autostart
install -d -m 0700 $HOME/Desktop/Trash
install -d -m 0700 $HOME/Desktop/Templates

echo
echo "Copying desktop configuration"
echo

install -m 0644 $KDEDIR/lib/kfm/Desktop/Templates/* $HOME/Desktop/Templates
install -m 0644 $KDEDIR/lib/kfm/Desktop/*.kdelnk $HOME/Desktop
install -m 0644 $KDEDIR/lib/kfm/config/kfmrc $HOME/.kfmrc

echo
echo "Installation completed"