#!/bin/sh
# It looks like the sleeps do speed up the startup time
(sleep 1 && exec kaudioserver) &
(sleep 1 && exec kwmsound) &

(sleep 1 && exec kfm) &
(sleep 2 && exec kcontrol -init) &

(sleep 1 && exec krootwm) &
(sleep 1 && exec kpanel) &
(sleep 3 && exec kbgndwm) &
sleep 2 ; exec kwm
