#!/bin/sh
#
#  DEFAULT KDE STARTUP SCRIPT ( KDE-1.1 )
#

# initialize the configuration first.

exec kcontrol -init

# Start the common desktop tools in the background.
# The sleeps reduce disk usage during startup.

(sleep 1 && exec kaudioserver) &
(sleep 1 && exec kwmsound) &

(sleep 1 && exec kfm) &

(sleep 1 && exec krootwm) &
(sleep 1 && exec kpanel) &
(sleep 3 && exec kbgndwm) &

# finally, give the session control to the window manager

sleep 2 ; exec kwm

