/**********************************************************************

	--- Dlgedit generated file ---

	File: DesktopPathDialogData.h
	Last generated: Tue Jul 15 18:07:10 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef DesktopPathDialogData_included
#define DesktopPathDialogData_included

#include <qdialog.h>
#include <qlined.h>
#include <qpushbt.h>

class DesktopPathDialogData : public QDialog
{
    Q_OBJECT

public:

    DesktopPathDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~DesktopPathDialogData();

public slots:


protected slots:


protected:
    QLineEdit* le_path;
    QLineEdit* le_ppath;
    QPushButton* b_ok;

};

#endif // DesktopPathDialogData_included
