/**********************************************************************

	--- Qt Architect generated file ---

	File: MenuNameDialogData.h
	Last generated: Fri Nov 28 14:52:53 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef MenuNameDialogData_included
#define MenuNameDialogData_included

#include <qdialog.h>
#include <qpushbt.h>
#include <qlined.h>

class MenuNameDialogData : public QDialog
{
    Q_OBJECT

public:

    MenuNameDialogData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~MenuNameDialogData();

public slots:


protected slots:


protected:
    QLineEdit* i_personal;
    QLineEdit* i_default;
    QPushButton* b_ok;
    QPushButton* b_cancel;

};

#endif // MenuNameDialogData_included
